config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, format: { with: /(\A([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*\Z)/i }

  attachment :avatar

  has_many :follower_relationships,  foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_relationships,  source: :follower

  has_many :following_relationships, foreign_key: :follower_id,  class_name: "Follow"
  has_many :following, through: :following_relationships, source: :following

  has_many :posts

  def follow(member)
    following_relationships.create(following_id: member.id)
  end

  def unfollow(member)
    following_relationships.find_by(following_id: member.id).destroy
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member, optional: true #optional true even means if there's no association it will save the record
  validates :caption, :presence => true

  attachment :posted_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
  puts "@DEBUG #{__LINE__}  Marked A"
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # member /members
  # member /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :mobile_phone, :avatar) #if you're addinng new parameter no need to add line just add it to params.require -commend added by me.
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :posted_image) #if you're addinng new parameter no need to add line just add it to params.require -commend added by me.
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaglam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: @member, local: true) do |form| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.attachment_field :avatar %>
  </div>

  <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, id: :post_first_name %>
    </div>

    <div class="field">
   <%= form.label :last_name %>
   <%= form.text_field :last_name, id: :post_last_name %>
 </div>

   <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, id: :post_email %>
    </div>

    <div class="field">
       <%= form.label :mobile_phone %>
       <%= form.text_field :mobile_phone, id: :mobile_phone %>
     </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Edit Profile</h1>

<nav>
  <ul>
    <li><h1>Instaglam</h1></li>
    <li><a href="home.html">Home</a></li>
    <li>Notification</li>
   <!--  <li><a href="profile.html">Profile</a></li> -->
    <li><%= link_to 'Profile', @member %></li>
    <li><a href="login.html">Log out</a></li>
  </ul>
  </nav>

<%= render 'form', post: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1 align="center">members</h1> -->

<nav>
  <ul>
    <% @members.each do |member| %>
    <li><h1>Instaglam</h1></li>
    <!-- <li><a href="home.html">Home</a></li> -->
    <li><%= link_to 'Home', members_path %></li>
    <li>Notification</li>
   <!--  <li><a href="profile.html">Profile</a></li> -->
    <li><%= link_to 'Profile', member %></li>
    <li><a href="login.html">Log out</a></li>
     <% end %>
  </ul>
</nav>

<!-- <table align="center" style="color: tomato;" border="1">
  <thead>
    <tr>
      <th colspan="8">Profile</th>
    </tr>
  </thead> -->

<!--   <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.email %></td>
        <td><%= member.mobile_phone %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td colspan="8" align="center"><%= image_tag attachment_url(member, :avatar, :fill, 300, 300, format: "jpg") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button style="a { text-decoration: none; }">
<%= link_to 'New member', new_member_path %>
</button> -->

<input type="button" value="upload picture"><br/><br/>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/400x600"></a><br/>
<input type="text" placeholder="comment" ><br/></br>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/400x600"></a><br/>
<input type="text" placeholder="comment" ><br/></br>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/400x600"></a><br/>
<input type="text" placeholder="comment" ><br/></br>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/400x600"></a><br/>
<input type="text" placeholder="comment" ><br/></br>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/400x600"></a>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= image_tag attachment_url(@member, :avatar, :fill, 300, 300, format: "jpg") %> </p>

  <nav>
  <ul>
    <li><h1>Instaglam</h1></li>
    <!-- <li><a href="home.html">Home</a></li> -->
    <li><%= link_to 'Home', members_path %></li>
    <li>Notification</li>
   <!--  <li><a href="profile.html">Profile</a></li> -->
    <li><%= link_to 'Profile', @member %></li>
    <li><a href="login.html">Log out</a></li>
  </ul>
  </nav>
<!-- <img src="img/profile.png" height="180px" width="180px"/> -->
<h2>Username</h2>
<!-- <a href="edit.html">Edit Profile</a> -->
<%= link_to 'Edit Profile', edit_member_path(@member) %>

<p>Description</p>
<h3>Post...</h3>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>
<a href="https://placeholder.com"><img src="http://via.placeholder.com/350x150"></a>

<!-- <p>
  <strong>Firstname:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @member.mobile_phone %>
</p> -->

<br>
<%= link_to 'Home', members_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :post_caption %>
    <%= form.attachment_field :posted_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Posts</h1>

<table align="center" style="color: tomato;">
  <thead>
    <tr>
      <th colspan="4">Pictures</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.caption %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td colspan="4"><%= image_tag attachment_url(post, :posted_image, :fill, 300, 300, format: "jpg") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @post.caption %>
  <%= image_tag attachment_url(@post, :posted_image, :fill, 300, 300, format: "jpg") %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>